### ISSUE TITLE
When are you planning to release the dataset?

### ISSUE THREAD

**Issue by linzhiqiu** [amitakamath/vl_text_encoders_are_bottlenecks#1]
We would like to try your new Winoground-like dataset! Please let me know when you are planning to release it.

**Comment by vishaal27** [comment]
Yes, I am quite excited to try it out too!

**Comment by amitakamath** [comment]
Thank you for your interest in our dataset! We'll be releasing the code within the next couple of weeks, and I'll try to get the data up sooner than that.

**Comment by Sreyan88** [comment]
Hi @amitakamath ,

Great work! When could we expect the dataset and the code to be released? Thank You!

**Comment by bpiyush** [comment]
+1 to data release! Looks like an interesting dataset.
